// Copyright 2025 KU Leuven.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

package snax_acc.versacore

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths

import chisel3._

import fp_unit._

// DualVersaCoreSwigluGen: generates all RTL for the dual-VersaCore SwiGLU accelerator
// - Generates VersaCore.sv (reused from single VersaCore)
// - Generates snax_dual_versacore_swiglu_shell_wrapper.sv
// - Copies shifter_6stage.sv, shifter_2stage.sv, elem_adder_32b.sv from resources
// - Generates C stationarity header

object DualVersaCoreSwigluGen {
  def main(args: Array[String]): Unit = {

    // Parse command-line arguments
    def parseArgs(args: Array[String]): Map[String, String] = {
      val parsed_args = args
        .sliding(2, 2)
        .collect {
          case Array(key, value) if key.startsWith("--") => key.drop(2) -> value
        }
        .toMap
      if (parsed_args.size != 2) {
        println(
          "Usage: --versacoreCfg <hjson string> --hw-target-dir <output dir>"
        )
        sys.exit(1)
      }
      parsed_args
    }

    val parsedArgs = parseArgs(args)

    val outPath = parsedArgs.getOrElse(
      "hw-target-dir",
      "generated/snax_dual_versacore_swiglu"
    )

    val versacoreCfg = parsedArgs.find(_._1 == "versacoreCfg").get._2

    val params = SpatialArrayParamParser.parseFromHjsonString(versacoreCfg)

    // Step 1: Generate VersaCore.sv (same as single VersaCore)
    var sv_string = getVerilogString(new VersaCore(params))

    sv_string = sv_string
      .split("\n")
      .takeWhile(
        !_.contains(
          """// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----"""
        )
      )
      .mkString("\n")

    val lines: Array[String] = sv_string.split("\n")
    val startIdx = lines.indexWhere(_.contains("package fpnew_pkg_snax"))

    if (startIdx != -1) {
      val endIdx = lines.indexWhere(_.trim == "endpackage", startIdx)
      if (endIdx != -1 && endIdx > startIdx) {
        val pkgBlock       = lines.slice(startIdx, endIdx + 1)
        val remainingLines = lines.take(startIdx) ++ lines.drop(endIdx + 1)
        sv_string = (pkgBlock ++ remainingLines).mkString("\n")
      }
    }

    val outFile = Paths.get(s"$outPath/VersaCore.sv")
    Files.createDirectories(outFile.getParent)
    Files.write(outFile, sv_string.getBytes(StandardCharsets.UTF_8))

    // Step 2: Copy SV resource files for post-processing modules
    val resourceFiles = Seq("shifter_6stage.sv", "shifter_2stage.sv", "elem_adder_32b.sv")
    for (resFile <- resourceFiles) {
      val resPath = s"/snax_acc/versacore/$resFile"
      val is = getClass.getResourceAsStream(resPath)
      if (is != null) {
        val content = scala.io.Source.fromInputStream(is)(scala.io.Codec.UTF8).mkString
        is.close()
        val targetFile = Paths.get(s"$outPath/$resFile")
        Files.write(targetFile, content.getBytes(StandardCharsets.UTF_8))
        println(s"Copied resource: $resFile -> $outPath/$resFile")
      } else {
        println(s"WARNING: Resource not found: $resPath")
      }
    }

    // Step 3: Generate the shell wrapper
    val DataWidthA = params.arrayInputAWidth
    val DataWidthB = params.arrayInputBWidth
    val DataWidthD = params.serialOutputDDataWidth

    // Parse postproc lanes from config (default 64)
    val cfg = ujson.read(versacoreCfg)
    val PostprocLanes = cfg.obj.get("snax_dual_versacore_postproc_lanes")
      .map(_.num.toInt).getOrElse(64)

    val header = s"""// Copyright 2025 KU Leuven.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Generated by DualVersaCoreSwigluGen at ${java.time.Instant.now()}
// Do not modify manually.
//
// Dual VersaCore SwiGLU shell wrapper
// Architecture: 2 VersaCores (shared A) + intermediate buffer + 6-stage/2-stage shifters + adder
"""

    val wrapperSv = header + s"""
module snax_dual_versacore_swiglu_shell_wrapper #(
    parameter int unsigned RegRWCount   = ${params.csrNum},
    parameter int unsigned RegROCount   = 2,
    parameter int unsigned DataWidthA   = $DataWidthA,
    parameter int unsigned DataWidthB   = $DataWidthB,
    parameter int unsigned DataWidthD   = $DataWidthD,
    parameter int unsigned PostprocLanes = $PostprocLanes,
    parameter int unsigned RegDataWidth = 32,
    parameter int unsigned RegAddrWidth = 32
) (
    //-------------------------------
    // Clocks and reset
    //-------------------------------
    input logic clk_i,
    input logic rst_ni,

    //-------------------------------
    // Accelerator ports
    //-------------------------------
    // acc2stream_0 = output (post-processed result to writer streamer)
    output logic [DataWidthD-1:0] acc2stream_0_data_o,
    output logic acc2stream_0_valid_o,
    input logic acc2stream_0_ready_i,

    // stream2acc_0 = Input A (shared by both VersaCores)
    input logic [DataWidthA-1:0] stream2acc_0_data_i,
    input logic stream2acc_0_valid_i,
    output logic stream2acc_0_ready_o,

    // stream2acc_1 = Input B0 (VersaCore 0)
    input logic [DataWidthB-1:0] stream2acc_1_data_i,
    input logic stream2acc_1_valid_i,
    output logic stream2acc_1_ready_o,

    // stream2acc_2 = Input B1 (VersaCore 1)
    input logic [DataWidthB-1:0] stream2acc_2_data_i,
    input logic stream2acc_2_valid_i,
    output logic stream2acc_2_ready_o,

    //-------------------------------
    // CSR manager ports
    //-------------------------------
    input  logic [RegRWCount-1:0][RegDataWidth-1:0] csr_reg_set_i,
    input  logic                                    csr_reg_set_valid_i,
    output logic                                    csr_reg_set_ready_o,
    output logic [RegROCount-1:0][RegDataWidth-1:0] csr_reg_ro_set_o
);

    // =========================================================================
    // Internal signals
    // =========================================================================

    // VersaCore 0 signals
    logic vc0_in_a_ready, vc0_in_a_valid;
    logic vc0_in_b_ready, vc0_in_b_valid;
    logic vc0_in_c_ready, vc0_in_c_valid;
    logic [DataWidthD-1:0] vc0_out_d_data;
    logic vc0_out_d_valid, vc0_out_d_ready;
    logic vc0_ctrl_ready;
    logic vc0_busy;
    logic [31:0] vc0_perf_counter;

    // VersaCore 1 signals
    logic vc1_in_a_ready, vc1_in_a_valid;
    logic vc1_in_b_ready, vc1_in_b_valid;
    logic vc1_in_c_ready, vc1_in_c_valid;
    logic [DataWidthD-1:0] vc1_out_d_data;
    logic vc1_out_d_valid, vc1_out_d_ready;
    logic vc1_ctrl_ready;
    logic vc1_busy;
    logic [31:0] vc1_perf_counter;

    // Tie off C inputs (no partial sum accumulation)
    logic [${params.serialInputCDataWidth}-1:0] tied_c_data;
    assign tied_c_data = '0;

    // =========================================================================
    // Shared A synchronization
    // One-beat lockstep buffer for A:
    // - Accept one A beat from streamer
    // - Feed the same beat to both VersaCores
    // - Mark beat complete only after each core has consumed it once
    // This avoids valid/ready combinational cycles and prevents either core
    // from consuming an A beat multiple times before the other core consumes it.
    // =========================================================================
    logic [DataWidthA-1:0] a_buf_data;
    logic a_buf_valid;
    logic a_buf_sent_0;
    logic a_buf_sent_1;
    logic a_fire_0;
    logic a_fire_1;

    assign stream2acc_0_ready_o = !a_buf_valid;

    assign vc0_in_a_valid = a_buf_valid && !a_buf_sent_0;
    assign vc1_in_a_valid = a_buf_valid && !a_buf_sent_1;

    assign a_fire_0 = vc0_in_a_valid && vc0_in_a_ready;
    assign a_fire_1 = vc1_in_a_valid && vc1_in_a_ready;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            a_buf_valid <= 1'b0;
            a_buf_sent_0 <= 1'b0;
            a_buf_sent_1 <= 1'b0;
        end else begin
            if (!a_buf_valid) begin
                if (stream2acc_0_valid_i) begin
                    a_buf_valid <= 1'b1;
                    a_buf_data <= stream2acc_0_data_i;
                    a_buf_sent_0 <= 1'b0;
                    a_buf_sent_1 <= 1'b0;
                end
            end else begin
                if (a_fire_0) a_buf_sent_0 <= 1'b1;
                if (a_fire_1) a_buf_sent_1 <= 1'b1;

                if ((a_buf_sent_0 || a_fire_0) && (a_buf_sent_1 || a_fire_1)) begin
                    a_buf_valid <= 1'b0;
                end
            end
        end
    end

    // B0 -> VersaCore 0, B1 -> VersaCore 1
    assign stream2acc_1_ready_o = vc0_in_b_ready;
    assign vc0_in_b_valid = stream2acc_1_valid_i;

    assign stream2acc_2_ready_o = vc1_in_b_ready;
    assign vc1_in_b_valid = stream2acc_2_valid_i;

    // CSR control synchronization: both VersaCores must be ready
    logic ctrl_valid_to_vc;
    assign csr_reg_set_ready_o = vc0_ctrl_ready && vc1_ctrl_ready;
    assign ctrl_valid_to_vc = csr_reg_set_valid_i;

    // =========================================================================
    // VersaCore 0
    // =========================================================================
    VersaCore inst_VersaCore_0 (
        .clock(clk_i),
        .reset(~rst_ni),

        .io_versacore_data_in_a_ready(vc0_in_a_ready),
        .io_versacore_data_in_a_valid(vc0_in_a_valid),
        .io_versacore_data_in_a_bits (a_buf_data),

        .io_versacore_data_in_b_ready(vc0_in_b_ready),
        .io_versacore_data_in_b_valid(vc0_in_b_valid),
        .io_versacore_data_in_b_bits (stream2acc_1_data_i),

        .io_versacore_data_in_c_ready(vc0_in_c_ready),
        .io_versacore_data_in_c_valid(1'b1),
        .io_versacore_data_in_c_bits (tied_c_data),

        .io_versacore_data_out_d_ready(vc0_out_d_ready),
        .io_versacore_data_out_d_valid(vc0_out_d_valid),
        .io_versacore_data_out_d_bits (vc0_out_d_data),

        .io_ctrl_ready(vc0_ctrl_ready),
        .io_ctrl_valid(ctrl_valid_to_vc),
        .io_ctrl_bits_fsmCfg_take_in_new_c(csr_reg_set_i[0]),
        .io_ctrl_bits_fsmCfg_a_b_input_times_one_output(csr_reg_set_i[1]),
        .io_ctrl_bits_fsmCfg_output_times(csr_reg_set_i[2]),
        .io_ctrl_bits_fsmCfg_subtraction_constant_i(csr_reg_set_i[3]),
        .io_ctrl_bits_arrayCfg_arrayShapeCfg(csr_reg_set_i[4]),
        .io_ctrl_bits_arrayCfg_dataTypeCfg(csr_reg_set_i[5]),

        .io_busy_o(vc0_busy),
        .io_performance_counter(vc0_perf_counter)
    );

    // =========================================================================
    // VersaCore 1
    // =========================================================================
    VersaCore inst_VersaCore_1 (
        .clock(clk_i),
        .reset(~rst_ni),

        .io_versacore_data_in_a_ready(vc1_in_a_ready),
        .io_versacore_data_in_a_valid(vc1_in_a_valid),
        .io_versacore_data_in_a_bits (a_buf_data),

        .io_versacore_data_in_b_ready(vc1_in_b_ready),
        .io_versacore_data_in_b_valid(vc1_in_b_valid),
        .io_versacore_data_in_b_bits (stream2acc_2_data_i),

        .io_versacore_data_in_c_ready(vc1_in_c_ready),
        .io_versacore_data_in_c_valid(1'b1),
        .io_versacore_data_in_c_bits (tied_c_data),

        .io_versacore_data_out_d_ready(vc1_out_d_ready),
        .io_versacore_data_out_d_valid(vc1_out_d_valid),
        .io_versacore_data_out_d_bits (vc1_out_d_data),

        .io_ctrl_ready(vc1_ctrl_ready),
        .io_ctrl_valid(ctrl_valid_to_vc),
        .io_ctrl_bits_fsmCfg_take_in_new_c(csr_reg_set_i[0]),
        .io_ctrl_bits_fsmCfg_a_b_input_times_one_output(csr_reg_set_i[1]),
        .io_ctrl_bits_fsmCfg_output_times(csr_reg_set_i[2]),
        .io_ctrl_bits_fsmCfg_subtraction_constant_i(csr_reg_set_i[3]),
        .io_ctrl_bits_arrayCfg_arrayShapeCfg(csr_reg_set_i[4]),
        .io_ctrl_bits_arrayCfg_dataTypeCfg(csr_reg_set_i[5]),

        .io_busy_o(vc1_busy),
        .io_performance_counter(vc1_perf_counter)
    );

    // =========================================================================
    // Dual independent buffers: one per path
    // Both VersaCores output in lockstep, captured by a joint handshake.
    // Each path then has its own buffer and chunk counter to feed its shifter
    // independently. This avoids deadlock from latency mismatch (6 vs 2 stages).
    // =========================================================================

    logic both_vc_out_valid;
    assign both_vc_out_valid = vc0_out_d_valid && vc1_out_d_valid;

    // --- Path 0 buffer (feeds 6-stage shifter) ---
    logic [DataWidthD-1:0] buf0_data;
    logic buf0_valid;
    logic buf0_out_ready;  // downstream can accept

    // --- Path 1 buffer (feeds 2-stage shifter) ---
    logic [DataWidthD-1:0] buf1_data;
    logic buf1_valid;
    logic buf1_out_ready;  // downstream can accept

    // Joint VersaCore output handshake: both buffers must be free to accept
    logic buf_can_accept;
    assign buf_can_accept = (!buf0_valid || buf0_out_ready) && (!buf1_valid || buf1_out_ready);

    assign vc0_out_d_ready = vc1_out_d_valid && buf_can_accept;
    assign vc1_out_d_ready = vc0_out_d_valid && buf_can_accept;

    logic buf_fire;
    assign buf_fire = both_vc_out_valid && buf_can_accept;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            buf0_valid <= 1'b0;
            buf1_valid <= 1'b0;
        end else begin
            // Buffer 0
            if (!buf0_valid || buf0_out_ready) begin
                buf0_valid <= buf_fire;
                if (buf_fire) buf0_data <= vc0_out_d_data;
            end
            // Buffer 1
            if (!buf1_valid || buf1_out_ready) begin
                buf1_valid <= buf_fire;
                if (buf_fire) buf1_data <= vc1_out_d_data;
            end
        end
    end

    // =========================================================================
    // Post-processing parameters
    // =========================================================================
    localparam int unsigned ElemsPerBeat = DataWidthD / 32;
    localparam int unsigned NumChunks = (ElemsPerBeat + PostprocLanes - 1) / PostprocLanes;

    // =========================================================================
    // Path 0: buffer -> chunk serializer -> 6-stage shifter
    // =========================================================================
    logic [$$clog2(NumChunks > 1 ? NumChunks : 2)-1:0] chunk_cnt_0;
    logic chunk_last_0;
    assign chunk_last_0 = (NumChunks <= 1) || (chunk_cnt_0 == NumChunks - 1);

    logic [PostprocLanes-1:0][31:0] shifter0_in_data;
    logic shifter0_in_valid;
    logic shifter0_in_ready;

    always_comb begin
        for (int i = 0; i < PostprocLanes; i++) begin
            int idx;
            idx = chunk_cnt_0 * PostprocLanes + i;
            if (idx < ElemsPerBeat)
                shifter0_in_data[i] = buf0_data[idx*32 +: 32];
            else
                shifter0_in_data[i] = '0;
        end
    end

    assign shifter0_in_valid = buf0_valid;
    assign buf0_out_ready = shifter0_in_ready && chunk_last_0;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            chunk_cnt_0 <= '0;
        end else begin
            if (buf0_valid && shifter0_in_ready) begin
                if (chunk_last_0)
                    chunk_cnt_0 <= '0;
                else
                    chunk_cnt_0 <= chunk_cnt_0 + 1;
            end
        end
    end

    // =========================================================================
    // Path 1: buffer -> chunk serializer -> 2-stage shifter
    // =========================================================================
    logic [$$clog2(NumChunks > 1 ? NumChunks : 2)-1:0] chunk_cnt_1;
    logic chunk_last_1;
    assign chunk_last_1 = (NumChunks <= 1) || (chunk_cnt_1 == NumChunks - 1);

    logic [PostprocLanes-1:0][31:0] shifter1_in_data;
    logic shifter1_in_valid;
    logic shifter1_in_ready;

    always_comb begin
        for (int i = 0; i < PostprocLanes; i++) begin
            int idx;
            idx = chunk_cnt_1 * PostprocLanes + i;
            if (idx < ElemsPerBeat)
                shifter1_in_data[i] = buf1_data[idx*32 +: 32];
            else
                shifter1_in_data[i] = '0;
        end
    end

    assign shifter1_in_valid = buf1_valid;
    assign buf1_out_ready = shifter1_in_ready && chunk_last_1;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            chunk_cnt_1 <= '0;
        end else begin
            if (buf1_valid && shifter1_in_ready) begin
                if (chunk_last_1)
                    chunk_cnt_1 <= '0;
                else
                    chunk_cnt_1 <= chunk_cnt_1 + 1;
            end
        end
    end

    // =========================================================================
    // Shifter instances
    // =========================================================================
    logic [PostprocLanes-1:0][31:0] shifter0_out_data;
    logic shifter0_out_valid, shifter0_out_ready;

    logic [PostprocLanes-1:0][31:0] shifter1_out_data;
    logic shifter1_out_valid, shifter1_out_ready;

    shifter_6stage #(
        .DATA_WIDTH(32),
        .NUM_LANES(PostprocLanes)
    ) u_shifter_6stage (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .data_i  (shifter0_in_data),
        .valid_i (shifter0_in_valid),
        .ready_o (shifter0_in_ready),
        .data_o  (shifter0_out_data),
        .valid_o (shifter0_out_valid),
        .ready_i (shifter0_out_ready)
    );

    shifter_2stage #(
        .DATA_WIDTH(32),
        .NUM_LANES(PostprocLanes)
    ) u_shifter_2stage (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .data_i  (shifter1_in_data),
        .valid_i (shifter1_in_valid),
        .ready_o (shifter1_in_ready),
        .data_o  (shifter1_out_data),
        .valid_o (shifter1_out_valid),
        .ready_i (shifter1_out_ready)
    );

    // =========================================================================
    // Element-wise adder
    // =========================================================================
    logic [PostprocLanes-1:0][31:0] adder_out_data;
    logic adder_out_valid, adder_out_ready;

    elem_adder_32b #(
        .NUM_LANES(PostprocLanes)
    ) u_elem_adder (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .data_i_0(shifter0_out_data),
        .valid_i_0(shifter0_out_valid),
        .ready_o_0(shifter0_out_ready),
        .data_i_1(shifter1_out_data),
        .valid_i_1(shifter1_out_valid),
        .ready_o_1(shifter1_out_ready),
        .data_o  (adder_out_data),
        .valid_o (adder_out_valid),
        .ready_i (adder_out_ready)
    );

    // =========================================================================
    // Output serialization: reassemble chunks into DataWidthD-bit output beats
    // =========================================================================
    logic [$$clog2(NumChunks > 1 ? NumChunks : 2)-1:0] out_chunk_cnt;
    logic out_chunk_last;
    assign out_chunk_last = (NumChunks <= 1) || (out_chunk_cnt == NumChunks - 1);

    logic [DataWidthD-1:0] out_assemble;
    logic out_assemble_valid;

    // Do not accept new adder chunks while a completed beat is pending on the
    // output streamer; this prevents overwriting `out_assemble`.
    assign adder_out_ready = !out_assemble_valid;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            out_chunk_cnt <= '0;
            out_assemble_valid <= 1'b0;
        end else begin
            if (adder_out_valid && adder_out_ready) begin
                for (int i = 0; i < PostprocLanes; i++) begin
                    int idx;
                    idx = out_chunk_cnt * PostprocLanes + i;
                    if (idx < ElemsPerBeat) begin
                        out_assemble[idx*32 +: 32] <= adder_out_data[i];
                    end
                end

                if (out_chunk_last) begin
                    out_chunk_cnt <= '0;
                    out_assemble_valid <= 1'b1;
                end else begin
                    out_chunk_cnt <= out_chunk_cnt + 1;
                    out_assemble_valid <= 1'b0;
                end
            end else if (out_assemble_valid && acc2stream_0_ready_i) begin
                out_assemble_valid <= 1'b0;
            end
        end
    end

    assign acc2stream_0_data_o = out_assemble;
    assign acc2stream_0_valid_o = out_assemble_valid;

    // =========================================================================
    // Read-only CSR outputs
    // =========================================================================
    // CSR RO[0]: busy (either VersaCore busy)
    assign csr_reg_ro_set_o[0] = {31'b0, vc0_busy || vc1_busy};
    // CSR RO[1]: performance counter (max of both)
    assign csr_reg_ro_set_o[1] = (vc0_perf_counter > vc1_perf_counter) ?
                                  vc0_perf_counter : vc1_perf_counter;

endmodule
"""

    val wrapperFile = Paths.get(s"$outPath/snax_dual_versacore_swiglu_shell_wrapper.sv")
    Files.write(wrapperFile, wrapperSv.getBytes(StandardCharsets.UTF_8))
    println(s"Generated wrapper file: $wrapperFile")

    // Step 4: Generate the C stationarity header
    val headerFile = s"$outPath/../../sw/snax/dual-versacore-swiglu/include/snax_dual_versacore_stationarity.h"

    val headerContent = s"""// Copyright 2025 KU Leuven.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by DualVersaCoreSwigluGen at ${java.time.Instant.now()}
// Do not modify manually.

#define SNAX_VERSACORE_OUTPUT_STATIONARY_ONLY
"""

    val headerPath: Path = Paths.get(headerFile)
    val headerParentDir = headerPath.getParent
    if (headerParentDir != null && !Files.exists(headerParentDir)) {
      Files.createDirectories(headerParentDir)
    }
    Files.write(headerPath, headerContent.getBytes(StandardCharsets.UTF_8))
    println(s"Generated header file: $headerFile")
  }
}
