// Copyright 2025 KU Leuven.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

package snax_acc.versacore

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths

import chisel3._

import fp_unit._

// DualVersaCoreSwigluGen: generates all RTL for the dual-VersaCore SwiGLU accelerator
// - Generates VersaCore.sv (reused from single VersaCore)
// - Generates snax_dual_versacore_swiglu_shell_wrapper.sv
// - Copies SV resource files for post-processing modules
// - Generates C stationarity header
//
// Mode 0 (SwiGLU): VC0→rescale0→silu_multilane(16b)→ElemMul16b←rescale1←VC1 → rescale_mul → Writer0
// Mode 1 (GEMM):   VC0→rescale0→Writer0, VC1→rescale1→Writer1

object DualVersaCoreSwigluGen {
  def main(args: Array[String]): Unit = {

    // Parse command-line arguments
    def parseArgs(args: Array[String]): Map[String, String] = {
      val parsed_args = args
        .sliding(2, 2)
        .collect {
          case Array(key, value) if key.startsWith("--") => key.drop(2) -> value
        }
        .toMap
      if (parsed_args.size != 2) {
        println(
          "Usage: --versacoreCfg <hjson string> --hw-target-dir <output dir>"
        )
        sys.exit(1)
      }
      parsed_args
    }

    val parsedArgs = parseArgs(args)

    val outPath = parsedArgs.getOrElse(
      "hw-target-dir",
      "generated/snax_dual_versacore_swiglu"
    )

    val versacoreCfg = parsedArgs.find(_._1 == "versacoreCfg").get._2

    val params = SpatialArrayParamParser.parseFromHjsonString(versacoreCfg)

    // Step 1: Generate VersaCore.sv (same as single VersaCore)
    var sv_string = getVerilogString(new VersaCore(params))

    sv_string = sv_string
      .split("\n")
      .takeWhile(
        !_.contains(
          """// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----"""
        )
      )
      .mkString("\n")

    val lines: Array[String] = sv_string.split("\n")
    val startIdx = lines.indexWhere(_.contains("package fpnew_pkg_snax"))

    if (startIdx != -1) {
      val endIdx = lines.indexWhere(_.trim == "endpackage", startIdx)
      if (endIdx != -1 && endIdx > startIdx) {
        val pkgBlock       = lines.slice(startIdx, endIdx + 1)
        val remainingLines = lines.take(startIdx) ++ lines.drop(endIdx + 1)
        sv_string = (pkgBlock ++ remainingLines).mkString("\n")
      }
    }

    val outFile = Paths.get(s"$outPath/VersaCore.sv")
    Files.createDirectories(outFile.getParent)
    Files.write(outFile, sv_string.getBytes(StandardCharsets.UTF_8))

    // Step 2: Copy SV resource files for post-processing modules
    val resourceFiles = Seq(
      "silu_out16_balanced_pkg.sv",
      "silu_multilane.sv",
      "silu_top.sv",
      "partition_detector.sv",
      "param_selector.sv",
      "horner_stage.sv",
      "rescale_down_32to16.sv",
      "elem_mul_16b.sv"
    )
    for (resFile <- resourceFiles) {
      val resPath = s"/snax_acc/versacore/$resFile"
      val is = getClass.getResourceAsStream(resPath)
      if (is != null) {
        val content = scala.io.Source.fromInputStream(is)(scala.io.Codec.UTF8).mkString
        is.close()
        val targetFile = Paths.get(s"$outPath/$resFile")
        Files.write(targetFile, content.getBytes(StandardCharsets.UTF_8))
        println(s"Copied resource: $resFile -> $outPath/$resFile")
      } else {
        println(s"WARNING: Resource not found: $resPath")
      }
    }

    // Step 3: Generate the shell wrapper
    val DataWidthA = params.arrayInputAWidth
    val DataWidthB = params.arrayInputBWidth
    val DataWidthD = params.serialOutputDDataWidth

    // Parse postproc lanes from config (default 64)
    val cfg = ujson.read(versacoreCfg)
    val PostprocLanes = cfg.obj.get("snax_dual_versacore_postproc_lanes")
      .map(_.num.toInt).getOrElse(64)

    // Writer-facing output width is the post-process chunk width.
    // The old DataWidthD / 2 formula only worked when PostprocLanes happened to
    // cover a whole int16 tile in one beat.
    val DataWidthOut = PostprocLanes * 16
    val activeChunkCases = params.arrayDim.head.zipWithIndex.map { case (dim, idx) =>
      val meshRow = dim(0)
      val meshCol = dim(2)
      val chunks  = (meshRow * meshCol + PostprocLanes - 1) / PostprocLanes
      s"            32'd$idx: active_num_chunks = $chunks;  // meshRow=$meshRow, meshCol=$meshCol"
    }.mkString("\n")

    val header = s"""// Copyright 2025 KU Leuven.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Generated by DualVersaCoreSwigluGen at ${java.time.Instant.now()}
// Do not modify manually.
//
// Dual VersaCore SwiGLU shell wrapper
// Mode 0 (SwiGLU): VC0->rescale0->silu_multilane(16b)->ElemMul16b<-rescale1<-VC1 -> rescale_mul -> Writer0
// Mode 1 (GEMM):   VC0->rescale0->Writer0, VC1->rescale1->Writer1
"""

    val wrapperSv = header + s"""
module snax_dual_versacore_swiglu_shell_wrapper #(
    parameter int unsigned RegRWCount   = 20,
    parameter int unsigned RegROCount   = 2,
    parameter int unsigned DataWidthA   = $DataWidthA,
    parameter int unsigned DataWidthB   = $DataWidthB,
    parameter int unsigned DataWidthD   = $DataWidthD,
    parameter int unsigned DataWidthOut = $DataWidthOut,
    parameter int unsigned PostprocLanes = $PostprocLanes,
    parameter int unsigned RegDataWidth = 32,
    parameter int unsigned RegAddrWidth = 32
) (
    //-------------------------------
    // Clocks and reset
    //-------------------------------
    input logic clk_i,
    input logic rst_ni,

    //-------------------------------
    // Accelerator ports
    //-------------------------------
    // acc2stream_0 = output 0 (Writer 0)
    output logic [DataWidthOut-1:0] acc2stream_0_data_o,
    output logic acc2stream_0_valid_o,
    input logic acc2stream_0_ready_i,

    // acc2stream_1 = output 1 (Writer 1)
    output logic [DataWidthOut-1:0] acc2stream_1_data_o,
    output logic acc2stream_1_valid_o,
    input logic acc2stream_1_ready_i,

    // stream2acc_0 = Input A (shared by both VersaCores)
    input logic [DataWidthA-1:0] stream2acc_0_data_i,
    input logic stream2acc_0_valid_i,
    output logic stream2acc_0_ready_o,

    // stream2acc_1 = Input B0 (VersaCore 0)
    input logic [DataWidthB-1:0] stream2acc_1_data_i,
    input logic stream2acc_1_valid_i,
    output logic stream2acc_1_ready_o,

    // stream2acc_2 = Input B1 (VersaCore 1)
    input logic [DataWidthB-1:0] stream2acc_2_data_i,
    input logic stream2acc_2_valid_i,
    output logic stream2acc_2_ready_o,

    //-------------------------------
    // CSR manager ports
    //-------------------------------
    input  logic [RegRWCount-1:0][RegDataWidth-1:0] csr_reg_set_i,
    input  logic                                    csr_reg_set_valid_i,
    output logic                                    csr_reg_set_ready_o,
    output logic [RegROCount-1:0][RegDataWidth-1:0] csr_reg_ro_set_o
);

    // =========================================================================
    // CSR extraction
    // =========================================================================
    // CSR[0]: OVERWRITE_ACCUM
    // CSR[1]: ACCUM_BOUND (a_b_input_times_one_output)
    // CSR[2]: OUTPUT_BOUND (output_times)
    // CSR[3]: SUBTRACTIONS
    // CSR[4]: ARRAY_SHAPE_CFG
    // CSR[5]: DATA_TYPE_CFG
    // CSR[6]: MODE (0=SwiGLU, 1=GEMM)
    // CSR[7..10]: RESCALE0 (input_zp, multiplier, output_zp, shift)
    // CSR[11..14]: RESCALE1 (input_zp, multiplier, output_zp, shift)
    // CSR[15..18]: RESCALE_MUL (input_zp, multiplier, output_zp, shift)
    // CSR[19]: START (handled by framework)

    logic mode_sel;
    assign mode_sel = csr_reg_set_i[6][0];

    // Rescale0 parameters
    logic signed [31:0] rescale0_input_zp;
    logic        [31:0] rescale0_multiplier;
    logic signed [31:0] rescale0_output_zp;
    logic        [7:0]  rescale0_shift;
    assign rescale0_input_zp   = csr_reg_set_i[7];
    assign rescale0_multiplier = csr_reg_set_i[8];
    assign rescale0_output_zp  = csr_reg_set_i[9];
    assign rescale0_shift      = csr_reg_set_i[10][7:0];

    // Rescale1 parameters
    logic signed [31:0] rescale1_input_zp;
    logic        [31:0] rescale1_multiplier;
    logic signed [31:0] rescale1_output_zp;
    logic        [7:0]  rescale1_shift;
    assign rescale1_input_zp   = csr_reg_set_i[11];
    assign rescale1_multiplier = csr_reg_set_i[12];
    assign rescale1_output_zp  = csr_reg_set_i[13];
    assign rescale1_shift      = csr_reg_set_i[14][7:0];

    // Rescale_mul parameters
    logic signed [31:0] rescale_mul_input_zp;
    logic        [31:0] rescale_mul_multiplier;
    logic signed [31:0] rescale_mul_output_zp;
    logic        [7:0]  rescale_mul_shift;
    assign rescale_mul_input_zp   = csr_reg_set_i[15];
    assign rescale_mul_multiplier = csr_reg_set_i[16];
    assign rescale_mul_output_zp  = csr_reg_set_i[17];
    assign rescale_mul_shift      = csr_reg_set_i[18][7:0];

    // =========================================================================
    // Internal signals
    // =========================================================================

    // VersaCore 0 signals
    logic vc0_in_a_ready, vc0_in_a_valid;
    logic vc0_in_b_ready, vc0_in_b_valid;
    logic vc0_in_c_ready, vc0_in_c_valid;
    logic [DataWidthD-1:0] vc0_out_d_data;
    logic vc0_out_d_valid, vc0_out_d_ready;
    logic vc0_ctrl_ready;
    logic vc0_busy;
    logic [31:0] vc0_perf_counter;

    // VersaCore 1 signals
    logic vc1_in_a_ready, vc1_in_a_valid;
    logic vc1_in_b_ready, vc1_in_b_valid;
    logic vc1_in_c_ready, vc1_in_c_valid;
    logic [DataWidthD-1:0] vc1_out_d_data;
    logic vc1_out_d_valid, vc1_out_d_ready;
    logic vc1_ctrl_ready;
    logic vc1_busy;
    logic [31:0] vc1_perf_counter;

    // Tie off C inputs (no partial sum accumulation)
    logic [${params.serialInputCDataWidth}-1:0] tied_c_data;
    assign tied_c_data = '0;

    // =========================================================================
    // Shared A synchronization
    // =========================================================================
    logic [DataWidthA-1:0] a_buf_data;
    logic a_buf_valid;
    logic a_buf_sent_0;
    logic a_buf_sent_1;
    logic a_fire_0;
    logic a_fire_1;
    logic a_buf_done;

    assign vc0_in_a_valid = a_buf_valid && !a_buf_sent_0;
    assign vc1_in_a_valid = a_buf_valid && !a_buf_sent_1;

    assign a_fire_0 = vc0_in_a_valid && vc0_in_a_ready;
    assign a_fire_1 = vc1_in_a_valid && vc1_in_a_ready;
    assign a_buf_done = a_buf_valid &&
                        (a_buf_sent_0 || a_fire_0) &&
                        (a_buf_sent_1 || a_fire_1);

    assign stream2acc_0_ready_o = !a_buf_valid || a_buf_done;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            a_buf_valid <= 1'b0;
            a_buf_sent_0 <= 1'b0;
            a_buf_sent_1 <= 1'b0;
        end else begin
            if (!a_buf_valid || a_buf_done) begin
                if (stream2acc_0_valid_i) begin
                    a_buf_valid <= 1'b1;
                    a_buf_data <= stream2acc_0_data_i;
                    a_buf_sent_0 <= 1'b0;
                    a_buf_sent_1 <= 1'b0;
                end else begin
                    a_buf_valid <= 1'b0;
                    a_buf_sent_0 <= 1'b0;
                    a_buf_sent_1 <= 1'b0;
                end
            end else begin
                if (a_fire_0) a_buf_sent_0 <= 1'b1;
                if (a_fire_1) a_buf_sent_1 <= 1'b1;
            end
        end
    end

    // B0 -> VersaCore 0, B1 -> VersaCore 1
    assign stream2acc_1_ready_o = vc0_in_b_ready;
    assign vc0_in_b_valid = stream2acc_1_valid_i;

    assign stream2acc_2_ready_o = vc1_in_b_ready;
    assign vc1_in_b_valid = stream2acc_2_valid_i;

    // CSR control synchronization: both VersaCores must be ready
    logic ctrl_valid_to_vc;
    assign csr_reg_set_ready_o = vc0_ctrl_ready && vc1_ctrl_ready;
    assign ctrl_valid_to_vc = csr_reg_set_valid_i;

    // =========================================================================
    // VersaCore 0
    // =========================================================================
    VersaCore inst_VersaCore_0 (
        .clock(clk_i),
        .reset(~rst_ni),

        .io_versacore_data_in_a_ready(vc0_in_a_ready),
        .io_versacore_data_in_a_valid(vc0_in_a_valid),
        .io_versacore_data_in_a_bits (a_buf_data),

        .io_versacore_data_in_b_ready(vc0_in_b_ready),
        .io_versacore_data_in_b_valid(vc0_in_b_valid),
        .io_versacore_data_in_b_bits (stream2acc_1_data_i),

        .io_versacore_data_in_c_ready(vc0_in_c_ready),
        .io_versacore_data_in_c_valid(1'b1),
        .io_versacore_data_in_c_bits (tied_c_data),

        .io_versacore_data_out_d_ready(vc0_out_d_ready),
        .io_versacore_data_out_d_valid(vc0_out_d_valid),
        .io_versacore_data_out_d_bits (vc0_out_d_data),

        .io_ctrl_ready(vc0_ctrl_ready),
        .io_ctrl_valid(ctrl_valid_to_vc),
        .io_ctrl_bits_fsmCfg_take_in_new_c(csr_reg_set_i[0]),
        .io_ctrl_bits_fsmCfg_a_b_input_times_one_output(csr_reg_set_i[1]),
        .io_ctrl_bits_fsmCfg_output_times(csr_reg_set_i[2]),
        .io_ctrl_bits_fsmCfg_subtraction_constant_i(csr_reg_set_i[3]),
        .io_ctrl_bits_arrayCfg_arrayShapeCfg(csr_reg_set_i[4]),
        .io_ctrl_bits_arrayCfg_dataTypeCfg(csr_reg_set_i[5]),

        .io_busy_o(vc0_busy),
        .io_performance_counter(vc0_perf_counter)
    );

    // =========================================================================
    // VersaCore 1
    // =========================================================================
    VersaCore inst_VersaCore_1 (
        .clock(clk_i),
        .reset(~rst_ni),

        .io_versacore_data_in_a_ready(vc1_in_a_ready),
        .io_versacore_data_in_a_valid(vc1_in_a_valid),
        .io_versacore_data_in_a_bits (a_buf_data),

        .io_versacore_data_in_b_ready(vc1_in_b_ready),
        .io_versacore_data_in_b_valid(vc1_in_b_valid),
        .io_versacore_data_in_b_bits (stream2acc_2_data_i),

        .io_versacore_data_in_c_ready(vc1_in_c_ready),
        .io_versacore_data_in_c_valid(1'b1),
        .io_versacore_data_in_c_bits (tied_c_data),

        .io_versacore_data_out_d_ready(vc1_out_d_ready),
        .io_versacore_data_out_d_valid(vc1_out_d_valid),
        .io_versacore_data_out_d_bits (vc1_out_d_data),

        .io_ctrl_ready(vc1_ctrl_ready),
        .io_ctrl_valid(ctrl_valid_to_vc),
        .io_ctrl_bits_fsmCfg_take_in_new_c(csr_reg_set_i[0]),
        .io_ctrl_bits_fsmCfg_a_b_input_times_one_output(csr_reg_set_i[1]),
        .io_ctrl_bits_fsmCfg_output_times(csr_reg_set_i[2]),
        .io_ctrl_bits_fsmCfg_subtraction_constant_i(csr_reg_set_i[3]),
        .io_ctrl_bits_arrayCfg_arrayShapeCfg(csr_reg_set_i[4]),
        .io_ctrl_bits_arrayCfg_dataTypeCfg(csr_reg_set_i[5]),

        .io_busy_o(vc1_busy),
        .io_performance_counter(vc1_perf_counter)
    );

    // =========================================================================
    // Dual independent buffers: one per path
    // =========================================================================

    logic both_vc_out_valid;
    assign both_vc_out_valid = vc0_out_d_valid && vc1_out_d_valid;

    // --- Path 0 buffer (feeds rescale0) ---
    logic [DataWidthD-1:0] buf0_data;
    logic buf0_valid;
    logic buf0_out_ready;

    // --- Path 1 buffer (feeds rescale1) ---
    logic [DataWidthD-1:0] buf1_data;
    logic buf1_valid;
    logic buf1_out_ready;

    // Joint VersaCore output handshake
    logic buf_can_accept;
    assign buf_can_accept = (!buf0_valid || buf0_out_ready) && (!buf1_valid || buf1_out_ready);

    assign vc0_out_d_ready = vc1_out_d_valid && buf_can_accept;
    assign vc1_out_d_ready = vc0_out_d_valid && buf_can_accept;

    logic buf_fire;
    assign buf_fire = both_vc_out_valid && buf_can_accept;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            buf0_valid <= 1'b0;
            buf1_valid <= 1'b0;
        end else begin
            if (!buf0_valid || buf0_out_ready) begin
                buf0_valid <= buf_fire;
                if (buf_fire) buf0_data <= vc0_out_d_data;
            end
            if (!buf1_valid || buf1_out_ready) begin
                buf1_valid <= buf_fire;
                if (buf_fire) buf1_data <= vc1_out_d_data;
            end
        end
    end

    // =========================================================================
    // Post-processing parameters
    // =========================================================================
    localparam int unsigned ElemsPerBeat = DataWidthD / 32;
    localparam int unsigned NumChunks = (ElemsPerBeat + PostprocLanes - 1) / PostprocLanes;

    function automatic logic [$$clog2(NumChunks + 1)-1:0]
        active_num_chunks(input logic [RegDataWidth-1:0] array_shape_cfg);
        case (array_shape_cfg)
$activeChunkCases
            default: active_num_chunks = NumChunks;
        endcase
    endfunction

    // =========================================================================
    // Path 0: buffer -> chunk serializer -> rescale0
    // =========================================================================
    logic [$$clog2(NumChunks > 1 ? NumChunks : 2)-1:0] chunk_cnt_0;
    logic chunk_last_0;
    assign chunk_last_0 = (NumChunks <= 1) ||
                          (chunk_cnt_0 == active_num_chunks(csr_reg_set_i[4]) - 1);

    logic [PostprocLanes-1:0][31:0] chunk_ser0_data;
    logic chunk_ser0_valid;
    logic chunk_ser0_ready;

    always_comb begin
        for (int i = 0; i < PostprocLanes; i++) begin
            int idx;
            idx = chunk_cnt_0 * PostprocLanes + i;
            if (idx < ElemsPerBeat)
                chunk_ser0_data[i] = buf0_data[idx*32 +: 32];
            else
                chunk_ser0_data[i] = '0;
        end
    end

    assign chunk_ser0_valid = buf0_valid;
    assign buf0_out_ready = chunk_ser0_ready && chunk_last_0;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            chunk_cnt_0 <= '0;
        end else begin
            if (buf0_valid && chunk_ser0_ready) begin
                if (chunk_last_0)
                    chunk_cnt_0 <= '0;
                else
                    chunk_cnt_0 <= chunk_cnt_0 + 1;
            end
        end
    end

    // =========================================================================
    // Path 1: buffer -> chunk serializer -> rescale1
    // =========================================================================
    logic [$$clog2(NumChunks > 1 ? NumChunks : 2)-1:0] chunk_cnt_1;
    logic chunk_last_1;
    assign chunk_last_1 = (NumChunks <= 1) ||
                          (chunk_cnt_1 == active_num_chunks(csr_reg_set_i[4]) - 1);

    logic [PostprocLanes-1:0][31:0] chunk_ser1_data;
    logic chunk_ser1_valid;
    logic chunk_ser1_ready;

    always_comb begin
        for (int i = 0; i < PostprocLanes; i++) begin
            int idx;
            idx = chunk_cnt_1 * PostprocLanes + i;
            if (idx < ElemsPerBeat)
                chunk_ser1_data[i] = buf1_data[idx*32 +: 32];
            else
                chunk_ser1_data[i] = '0;
        end
    end

    assign chunk_ser1_valid = buf1_valid;
    assign buf1_out_ready = chunk_ser1_ready && chunk_last_1;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            chunk_cnt_1 <= '0;
        end else begin
            if (buf1_valid && chunk_ser1_ready) begin
                if (chunk_last_1)
                    chunk_cnt_1 <= '0;
                else
                    chunk_cnt_1 <= chunk_cnt_1 + 1;
            end
        end
    end

    // =========================================================================
    // RescaleDown 0 (VC0 path): int32 -> int16
    // =========================================================================
    logic [PostprocLanes-1:0][15:0] rescale0_out_data;
    logic rescale0_out_valid, rescale0_out_ready;

    rescale_down_32to16 #(
        .NUM_LANES(PostprocLanes)
    ) u_rescale0 (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .input_zp   (rescale0_input_zp),
        .multiplier (rescale0_multiplier),
        .output_zp  (rescale0_output_zp),
        .shift      (rescale0_shift),
        .data_i     (chunk_ser0_data),
        .valid_i    (chunk_ser0_valid),
        .ready_o    (chunk_ser0_ready),
        .data_o     (rescale0_out_data),
        .valid_o    (rescale0_out_valid),
        .ready_i    (rescale0_out_ready)
    );

    // =========================================================================
    // RescaleDown 1 (VC1 path): int32 -> int16
    // =========================================================================
    logic [PostprocLanes-1:0][15:0] rescale1_out_data;
    logic rescale1_out_valid, rescale1_out_ready;

    rescale_down_32to16 #(
        .NUM_LANES(PostprocLanes)
    ) u_rescale1 (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .input_zp   (rescale1_input_zp),
        .multiplier (rescale1_multiplier),
        .output_zp  (rescale1_output_zp),
        .shift      (rescale1_shift),
        .data_i     (chunk_ser1_data),
        .valid_i    (chunk_ser1_valid),
        .ready_o    (chunk_ser1_ready),
        .data_o     (rescale1_out_data),
        .valid_o    (rescale1_out_valid),
        .ready_i    (rescale1_out_ready)
    );

    // =========================================================================
    // Real SiLU (balanced Q16.11, on rescale0 output)
    // Only used in Mode 0
    // =========================================================================
    logic [PostprocLanes-1:0][15:0] silu_out_data;
    logic silu_out_valid, silu_out_ready;

    // SiLU input: from rescale0 in mode 0, idle in mode 1
    logic [PostprocLanes-1:0][15:0] silu_in_data;
    logic silu_in_valid, silu_in_ready;

    assign silu_in_data  = rescale0_out_data;
    assign silu_in_valid = rescale0_out_valid && !mode_sel;  // only active in mode 0

    silu_multilane #(
        .NUM_LANES(PostprocLanes)
    ) u_silu_multilane (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .data_i  (silu_in_data),
        .valid_i (silu_in_valid),
        .ready_o (silu_in_ready),
        .data_o  (silu_out_data),
        .valid_o (silu_out_valid),
        .ready_i (silu_out_ready)
    );

    // =========================================================================
    // Element-wise multiplier (int16 x int16 -> int32)
    // Only used in Mode 0
    // =========================================================================
    logic [PostprocLanes-1:0][31:0] elem_mul_out_data;
    logic elem_mul_out_valid, elem_mul_out_ready;

    // ElemMul input 1: from rescale1 in mode 0, idle in mode 1
    logic elem_mul_in1_valid, elem_mul_in1_ready;
    assign elem_mul_in1_valid = rescale1_out_valid && !mode_sel;

    elem_mul_16b #(
        .NUM_LANES(PostprocLanes)
    ) u_elem_mul_16b (
        .clk_i   (clk_i),
        .rst_ni  (rst_ni),
        .data_i_0(silu_out_data),
        .valid_i_0(silu_out_valid),
        .ready_o_0(silu_out_ready),
        .data_i_1(rescale1_out_data),
        .valid_i_1(elem_mul_in1_valid),
        .ready_o_1(elem_mul_in1_ready),
        .data_o  (elem_mul_out_data),
        .valid_o (elem_mul_out_valid),
        .ready_i (elem_mul_out_ready)
    );

    // =========================================================================
    // RescaleDown MUL (after elem_mul): int32 -> int16
    // Only used in Mode 0
    // =========================================================================
    logic [PostprocLanes-1:0][15:0] rescale_mul_out_data;
    logic rescale_mul_out_valid, rescale_mul_out_ready;

    rescale_down_32to16 #(
        .NUM_LANES(PostprocLanes)
    ) u_rescale_mul (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .input_zp   (rescale_mul_input_zp),
        .multiplier (rescale_mul_multiplier),
        .output_zp  (rescale_mul_output_zp),
        .shift      (rescale_mul_shift),
        .data_i     (elem_mul_out_data),
        .valid_i    (elem_mul_out_valid),
        .ready_o    (elem_mul_out_ready),
        .data_o     (rescale_mul_out_data),
        .valid_o    (rescale_mul_out_valid),
        .ready_i    (rescale_mul_out_ready)
    );

    // =========================================================================
    // Mode mux: route rescale outputs to out_assemble paths
    // =========================================================================
    // Mode 0: rescale_mul -> out_assemble0, Writer1 idle
    // Mode 1: rescale0 -> out_assemble0, rescale1 -> out_assemble1

    // Signals feeding into out_assemble0
    logic [PostprocLanes-1:0][15:0] oa0_in_data;
    logic oa0_in_valid, oa0_in_ready;

    // Signals feeding into out_assemble1
    logic [PostprocLanes-1:0][15:0] oa1_in_data;
    logic oa1_in_valid, oa1_in_ready;

    always_comb begin
        if (mode_sel) begin
            // Mode 1 (GEMM): rescale0 -> out0, rescale1 -> out1
            oa0_in_data  = rescale0_out_data;
            oa0_in_valid = rescale0_out_valid;
            rescale0_out_ready = oa0_in_ready;

            oa1_in_data  = rescale1_out_data;
            oa1_in_valid = rescale1_out_valid;
            rescale1_out_ready = oa1_in_ready;

            // In mode 1, silu/elem_mul/rescale_mul stay idle (valid=0 already from gating above)
            rescale_mul_out_ready = 1'b1;  // Don't backpressure unused rescale_mul
        end else begin
            // Mode 0 (SwiGLU): rescale_mul -> out0 only, Writer1 idle.
            oa0_in_data  = rescale_mul_out_data;
            oa0_in_valid = rescale_mul_out_valid;
            rescale_mul_out_ready = oa0_in_ready;

            oa1_in_data  = '0;
            oa1_in_valid = 1'b0;

            // rescale0 ready is driven by SiLU
            rescale0_out_ready = silu_in_ready;
            // rescale1 ready is driven by elem_mul
            rescale1_out_ready = elem_mul_in1_ready;
        end
    end

    // =========================================================================
    // Output assembly 0: reassemble chunks into DataWidthOut-bit beats (int16)
    // =========================================================================
    localparam int unsigned ElemsPerBeatOut = DataWidthOut / 16;

    localparam int unsigned OutChunks = (ElemsPerBeatOut + PostprocLanes - 1) / PostprocLanes;

    logic [$$clog2(OutChunks > 1 ? OutChunks : 2)-1:0] out_chunk_cnt_0;
    logic out_chunk_last_0;
    assign out_chunk_last_0 = (OutChunks <= 1) || (out_chunk_cnt_0 == OutChunks - 1);

    logic [DataWidthOut-1:0] out_assemble_0;
    logic out_assemble_0_valid;

    assign oa0_in_ready = !out_assemble_0_valid;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            out_chunk_cnt_0 <= '0;
            out_assemble_0_valid <= 1'b0;
        end else begin
            if (oa0_in_valid && oa0_in_ready) begin
                for (int i = 0; i < PostprocLanes; i++) begin
                    int idx;
                    idx = out_chunk_cnt_0 * PostprocLanes + i;
                    if (idx < ElemsPerBeatOut) begin
                        out_assemble_0[idx*16 +: 16] <= oa0_in_data[i];
                    end
                end

                if (out_chunk_last_0) begin
                    out_chunk_cnt_0 <= '0;
                    out_assemble_0_valid <= 1'b1;
                end else begin
                    out_chunk_cnt_0 <= out_chunk_cnt_0 + 1;
                    out_assemble_0_valid <= 1'b0;
                end
            end else if (out_assemble_0_valid && acc2stream_0_ready_i) begin
                out_assemble_0_valid <= 1'b0;
            end
        end
    end

    assign acc2stream_0_data_o = out_assemble_0;
    assign acc2stream_0_valid_o = out_assemble_0_valid;

    // =========================================================================
    // Output assembly 1: reassemble chunks into DataWidthOut-bit beats (int16)
    // =========================================================================
    logic [$$clog2(OutChunks > 1 ? OutChunks : 2)-1:0] out_chunk_cnt_1;
    logic out_chunk_last_1;
    assign out_chunk_last_1 = (OutChunks <= 1) || (out_chunk_cnt_1 == OutChunks - 1);

    logic [DataWidthOut-1:0] out_assemble_1;
    logic out_assemble_1_valid;

    assign oa1_in_ready = !out_assemble_1_valid;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            out_chunk_cnt_1 <= '0;
            out_assemble_1_valid <= 1'b0;
        end else begin
            if (oa1_in_valid && oa1_in_ready) begin
                for (int i = 0; i < PostprocLanes; i++) begin
                    int idx;
                    idx = out_chunk_cnt_1 * PostprocLanes + i;
                    if (idx < ElemsPerBeatOut) begin
                        out_assemble_1[idx*16 +: 16] <= oa1_in_data[i];
                    end
                end

                if (out_chunk_last_1) begin
                    out_chunk_cnt_1 <= '0;
                    out_assemble_1_valid <= 1'b1;
                end else begin
                    out_chunk_cnt_1 <= out_chunk_cnt_1 + 1;
                    out_assemble_1_valid <= 1'b0;
                end
            end else if (out_assemble_1_valid && acc2stream_1_ready_i) begin
                out_assemble_1_valid <= 1'b0;
            end
        end
    end

    assign acc2stream_1_data_o = out_assemble_1;
    assign acc2stream_1_valid_o = out_assemble_1_valid;

    // =========================================================================
    // Read-only CSR outputs
    // =========================================================================
    // CSR RO[0]: busy (either VersaCore busy)
    assign csr_reg_ro_set_o[0] = {31'b0, vc0_busy || vc1_busy};
    // CSR RO[1]: performance counter (max of both)
    assign csr_reg_ro_set_o[1] = (vc0_perf_counter > vc1_perf_counter) ?
                                  vc0_perf_counter : vc1_perf_counter;

endmodule
"""

    val wrapperFile = Paths.get(s"$outPath/snax_dual_versacore_swiglu_shell_wrapper.sv")
    Files.write(wrapperFile, wrapperSv.getBytes(StandardCharsets.UTF_8))
    println(s"Generated wrapper file: $wrapperFile")

    // Step 4: Generate the C stationarity header
    val headerFile = s"$outPath/../../sw/snax/dual-versacore-swiglu/include/snax_dual_versacore_stationarity.h"

    val headerContent = s"""// Copyright 2025 KU Leuven.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by DualVersaCoreSwigluGen at ${java.time.Instant.now()}
// Do not modify manually.

#define SNAX_VERSACORE_OUTPUT_STATIONARY_ONLY
"""

    val headerPath: Path = Paths.get(headerFile)
    val headerParentDir = headerPath.getParent
    if (headerParentDir != null && !Files.exists(headerParentDir)) {
      Files.createDirectories(headerParentDir)
    }
    Files.write(headerPath, headerContent.getBytes(StandardCharsets.UTF_8))
    println(s"Generated header file: $headerFile")
  }
}
